### PR TITLE
Update 50-usb-serial.rules

### PR DESCRIPTION
**Pull request by rojas70**
The current udev rules does not allow us to identify dynamixel_ttl. We think this new rule may be more dependable.

### CODE REVIEW

**Comment by davetcoleman** [comment]
I know there are dependability issues with the serial interface on the ClamArm, but are you sure this is the best approach? Does `KERNEL=ttyUSB0` and `KERNEL=ttyUSB1` lock you into a certain ordering of USB plug-ins or locations? This seems less flexible, but I do not really know.

**Comment by rojas70** [comment]
We are having trouble talking to the motors. I do not know what is the
problem.

When we used the interface you provided, we could only see the
dynamixel_rs484 device but not the ttl. Some students got to see both
devices with the above rule but it did lock the ordering or the USB plugins.

Right now when we run clam_bringup we can't seem to be able to open the
device and find the motors.

[ERROR] [1403509786.130510390]: SerialPort::BaudToConstant() Invalid baud
rate: 57142
[ERROR] [1403509786.139383019]: Failed to open device /dev/dynamixel_ttl
with error: (2) No such file or directory
[FATAL] [1403509786.140655568]: No motors found on any configured serial
port, aborting

I am trying to set different baud rates.

---

Dr. Juan Rojas
SYSU Assistant Professor
School of Software,
Sun Yat-Sen University
_http://ss.sysu.edu.cn/~Rojas http://ss.sysu.edu.cn/~Rojas_

**Comment by rojas70** [comment]
Dave,

Sorry to bother you. Quick question. Did you have to install a driver for
the dynamixel's in linux? I can't recognized all devices as is, I also
noted that I have no folder called ftdi_sio, and I have been looking at the
following driver's tutorial:
http://support.robotis.com/en/software/dynamixel_sdk/usb2dynamixel/usb2dxl_linux.htm
.

A quick pointer would be appreciated.
Thanks

---

Dr. Juan Rojas
SYSU Assistant Professor
School of Software,
Sun Yat-Sen University
_http://ss.sysu.edu.cn/~Rojas http://ss.sysu.edu.cn/~Rojas_

**Comment by davetcoleman** [comment]
I always had issues with this too, but they were usually resolved unplugging and re-plugging back in, in varying orders. I never fully understood it. I think you'll need to contact dynamixel.

**Comment by davetcoleman** [comment]
Can you instead change this PR to add a new file called something like `50-usb-serial.rules.alternative` so that users can try both and see what their mileage is like?

**Pull request closed without merging**
